server:
  port: 7788

spring:
  application:
    name: mango-bkl

  # 是否延迟Bean的初始化，spring的配置
  # false: 默认值，表示禁用延迟初始化，即所有单例 Bean 在应用启动时就会被创建和注入。
  # true 表示开启延迟初始化，Bean 只有在第一次被使用时才会创建
  main:
    lazy-initialization: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mg_bkl?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver